# Generated by Django 2.2.12 on 2024-12-26 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20241220_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentreponse',
            options={},
        ),
        migrations.RemoveField(
            model_name='studentreponse',
            name='date_add',
        ),
        migrations.RemoveField(
            model_name='studentreponse',
            name='date_update',
        ),
        migrations.AlterField(
            model_name='studentreponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
