from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index_student"),
    path('fixed_student_account_billing_payment_information', views.fixed_student_account_billing_payment_information, name='fixed-student-account-billing-payment-information'),
    path('fixed_student_account_billing_subscription', views.fixed_student_account_billing_subscription, name='fixed-student-account-billing-subscription'),
    path('fixed_student_account_billing_upgrade', views.fixed_student_account_billing_upgrade, name='fixed-student-account-billing-upgrade'),
    path('fixed_student_account_edit', views.fixed_student_account_edit, name='fixed-student-account-edit'),
    path('fixed_student_account_edit_basic', views.fixed_student_account_edit_basic, name='fixed-student-account-edit-basic'),
    path('fixed_student_account_edit_profile', views.fixed_student_account_edit_profile, name='fixed-student-account-edit-profile'),
    path('fixed_student_billing', views.fixed_student_billing, name='fixed-student-billing'),
    path('fixed_student_browse_courses', views.fixed_student_browse_courses, name='fixed-student-browse-courses'),
    path('fixed_student_cart', views.fixed_student_cart, name='fixed-student-cart'),
    path('fixed_student_courses', views.fixed_student_courses, name='fixed-student-courses'),
    path('fixed_student_courses', views.fixed_student_courses, name='fixed-student-courses'),
    path('fixed_student_earnings', views.fixed_student_earnings, name='fixed-student-earnings'),
    path('fixed_student_forum', views.fixed_student_forum, name='fixed-student-forum'),
    path('fixed_student_forum_ask', views.fixed_student_forum_ask, name='fixed-student-forum-ask'),
    path('fixed_student_forum_thread', views.fixed_student_forum_thread, name='fixed-student-forum-thread'),
    path('fixed_student_help_center', views.fixed_student_help_center, name='fixed-student-help-center'),
    path('fixed_student_messages', views.fixed_student_messages, name='fixed-student-messages'),
    path('fixed_student_messages_2', views.fixed_student_messages_2, name='fixed-student-messages-2'),
    path('fixed_student_my_courses', views.fixed_student_my_courses, name='fixed-student-my-courses'),
    path('fixed_student_pay', views.fixed_student_pay, name='fixed-student-pay'),
    path('fixed_student_profile', views.fixed_student_profile, name='fixed-student-profile'),
    path('fixed_student_profile_posts', views.fixed_student_profile_posts, name='fixed-student-profile-posts'),
    path('fixed_student_quiz_results', views.fixed_student_quiz_results, name='fixed-student-quiz-results'),
    path('fixed_student_quizzes', views.fixed_student_quizzes, name='fixed-student-quizzes'),
    path('fixed_student_signup', views.fixed_student_signup, name='fixed-student-signup'),
    path('fixed_student_student_take_course', views.fixed_student_student_take_course, name='fixed-student-student-take-course'),
    path('fixed_student_take_course', views.fixed_student_take_course, name='fixed-student-take-course'),
    path('fixed_student_take_quiz', views.fixed_student_take_quiz, name='fixed-student-take-quiz'),
    path('fixed_student_view_course', views.fixed_student_view_course, name='fixed-student-view-course'),
]