# Generated by Django 2.2.12 on 2024-12-25 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_auto_20241225_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='instructeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='typequestion',
            field=models.CharField(choices=[('qcm', 'qcm'), ('question-reponse', 'question-reponse')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
