# Generated by Django 2.2.12 on 2024-12-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20241225_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='instructeur',
            new_name='instructor',
        ),
    ]
