# Generated by Django 2.2.12 on 2024-12-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20241226_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
