# Generated by Django 2.2.12 on 2024-12-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_questionresponse_quizresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='student',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_draft',
        ),
        migrations.DeleteModel(
            name='QuestionResponse',
        ),
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
