# Generated by Django 2.2.12 on 2024-12-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_quiz_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='classe',
        ),
    ]
