# Generated by Django 2.2.8 on 2020-04-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapitre',
            name='nombreCours',
        ),
        migrations.AddField(
            model_name='chapitre',
            name='date_debut',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='date_fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='duree_en_heure',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='video',
            field=models.FileField(null=True, upload_to='ressources/cours'),
        ),
    ]
