# Generated by Django 2.2.8 on 2020-04-21 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20200420_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classe_chapitre', to='school.Classe'),
        ),
    ]
