# Generated by Django 2.2.8 on 2020-04-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_chapitre_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='image',
            field=models.ImageField(null=True, upload_to='images/cours'),
        ),
        migrations.AddField(
            model_name='cours',
            name='pdf',
            field=models.FileField(null=True, upload_to='ressources/cours'),
        ),
        migrations.AddField(
            model_name='cours',
            name='video',
            field=models.FileField(null=True, upload_to='ressources/cours'),
        ),
    ]
