# Generated by Django 2.2.8 on 2020-04-22 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20200421_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='duree',
        ),
    ]
