# Generated by Django 2.2.8 on 2020-04-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_chapitre_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='description',
            field=models.TextField(default='Description du cours'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='image',
            field=models.ImageField(null=True, upload_to='images/matiere/'),
        ),
    ]
