# Generated by Django 2.2.12 on 2024-12-22 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0013_auto_20241220_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='instructeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to=settings.AUTH_USER_MODEL),
        ),
    ]
