# Generated by Django 2.2.12 on 2024-12-22 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_chapitre_instructeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapitre',
            name='instructeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
