# Generated by Django 2.2.12 on 2024-12-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0009_instructor_questions'),
        ('school', '0015_auto_20241222_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='instructor',
            field=models.ManyToManyField(blank=True, related_name='instructeur', to='instructor.Instructor'),
        ),
    ]
