# Generated by Django 2.2.8 on 2020-04-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_chapitre_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='image',
            field=models.ImageField(null=True, upload_to='images/chapitres'),
        ),
    ]
