# Generated by Django 2.2.12 on 2024-12-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20241220_1537'),
        ('instructor', '0005_instructor_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='matieres',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='school.Matiere'),
        ),
    ]
