# Generated by Django 2.2.12 on 2024-12-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_instructor_matieres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='matieres',
            field=models.ManyToManyField(related_name='instructors', to='school.Matiere'),
        ),
    ]
