# Generated by Django 2.2.12 on 2024-12-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0007_auto_20241221_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='matieres',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='school.Matiere'),
        ),
    ]
