# Generated by Django 2.2.12 on 2024-12-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20241225_1656'),
        ('instructor', '0008_auto_20241221_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='instructeur', to='quiz.Question'),
        ),
    ]
