# Generated by Django 2.2.8 on 2020-04-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_auto_20200420_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
